# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/busra/Vivado/ImageCompression/image_compression_communication/image_compression_communication.srcs/sources_1/bd/zynq_design/ip/zynq_design_processing_system7_0_0/zynq_design_processing_system7_0_0.xci
# IP: The module: 'zynq_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/busra/Vivado/ImageCompression/image_compression_communication/image_compression_communication.srcs/sources_1/bd/zynq_design/ip/zynq_design_processing_system7_0_0/zynq_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/busra/Vivado/ImageCompression/image_compression_communication/image_compression_communication.srcs/sources_1/bd/zynq_design/ip/zynq_design_processing_system7_0_0/zynq_design_processing_system7_0_0.xci
# IP: The module: 'zynq_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/busra/Vivado/ImageCompression/image_compression_communication/image_compression_communication.srcs/sources_1/bd/zynq_design/ip/zynq_design_processing_system7_0_0/zynq_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
